
export const decisions = [
  'Duplicate',
  'Not Duplicate',
  'Not Sure - Bad Data',
  'Combination of Duplicate & Not Duplicate',
  'Combination of Duplicate & Not Sure',
  'On Hold',
  'Combination of Not Duplicate & Not Sure',
  'Not Duplicate - Variant Data Not Available',
  'Not Duplicate - Different Compatibility',
  'Not Duplicate - Different Warranty',
  'Not Duplicate - Attribute Value Not Available',
  'Unpublish',
  'Combination of Duplicate, Not Duplicate & Not Sure'
];

export const sampleFeedbackData = [
  {
    id: 'FB001',
    formDate: '2024-03-15',
    formTime: '10:30 AM',
    formId: '1',
    agentEmail: 'john.doe@company.com',
    tlEmail: 'sarah.manager@company.com',
    gid: 'kdfkja',
    decision: 'Resolved',
    status: 'OPEN',
  },
  {
    id: 'FB002',
    formDate: '2024-03-16',
    formTime: '11:15 AM',
    formId: '2',
    agentEmail: 'emma.smith@company.com',
    tlEmail: 'david.boss@company.com',
    gid: 'gfh382',
    decision: 'Duplicate',
    status: 'CLOSED',
  },
  {
    id: 'FB003',
    formDate: '2024-03-17',
    formTime: '09:45 AM',
    formId: '3',
    agentEmail: 'michael.jones@company.com',
    tlEmail: 'sarah.manager@company.com',
    gid: 'hd73ks',
    decision: 'Not Duplicate',
    status: 'OPEN',
  },
  {
    id: 'FB004',
    formDate: '2024-03-18',
    formTime: '02:00 PM',
    formId: '4',
    agentEmail: 'lisa.wilson@company.com',
    tlEmail: 'david.boss@company.com',
    gid: '8sjk29',
    decision: 'On Hold',
    status: 'PENDING',
  },
  {
    id: 'FB005',
    formDate: '2024-03-19',
    formTime: '04:20 PM',
    formId: '5',
    agentEmail: 'robert.brown@company.com',
    tlEmail: 'sarah.manager@company.com',
    gid: '9fjskd',
    decision: 'Resolved',
    status: 'CLOSED',
  },
  {
    id: 'FB006',
    formDate: '2024-03-20',
    formTime: '01:10 PM',
    formId: '6',
    agentEmail: 'nancy.taylor@company.com',
    tlEmail: 'mark.lead@company.com',
    gid: 'ajd82k',
    decision: 'Not Sure - Bad Data',
    status: 'OPEN',
  },
  {
    id: 'FB007',
    formDate: '2024-03-21',
    formTime: '03:35 PM',
    formId: '7',
    agentEmail: 'steven.miller@company.com',
    tlEmail: 'david.boss@company.com',
    gid: '92ksl1',
    decision: 'Duplicate',
    status: 'CLOSED',
  },
  {
    id: 'FB008',
    formDate: '2024-03-22',
    formTime: '08:50 AM',
    formId: '8',
    agentEmail: 'olivia.davis@company.com',
    tlEmail: 'mark.lead@company.com',
    gid: 'dfh83m',
    decision: 'Resolved',
    status: 'OPEN',
  },
  {
    id: 'FB009',
    formDate: '2024-03-23',
    formTime: '12:40 PM',
    formId: '9',
    agentEmail: 'kevin.white@company.com',
    tlEmail: 'sarah.manager@company.com',
    gid: '3js8hd',
    decision: 'On Hold',
    status: 'PENDING',
  },
  {
    id: 'FB010',
    formDate: '2024-03-24',
    formTime: '05:25 PM',
    formId: '10',
    agentEmail: 'rachel.green@company.com',
    tlEmail: 'mark.lead@company.com',
    gid: 'skd92j',
    decision: 'Not Duplicate',
    status: 'OPEN',
  },
];


export const sampleData = []